version: '3'
services:
  mysql-service:
    container_name: mysql-service
    restart: always
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=root
    volumes:
      - "my-db:/var/lib/mysql"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  wealth-statement-service:
    container_name: wealth-statement-service
    image: wealth-statement-service:latest
    ports:
      - "10222:10222"
    depends_on:
      - mysql-service
    environment:
      - "SPRING_PROFILES_ACTIVE=qa"
# Names our volume
volumes:
  my-db: